#!/bin/sh
set -e -x

DIR="$1"
PART="$2"

run_jplc() {
    FILE="$1"
    ./jplc --eval "$DIR/$1"
}

compare_stdout() {
    FILE1="$1"
    FILE2="$2"
    diff "$FILE1" "$FILE2"
}

compare_png() {
    FILE1="$1"
    FILE2="$2"
    compare -metric AE -fuzz 1% "$FILE1" "$FILE2" null:
    ERR=$?
    echo
    return $ERR
}

sudo apt-get install -y imagemagick
cp hw1/sample.png sample.png

case $PART in
count)
    echo 6
    ;;
all)
    sh $0 $1 1
    sh $0 $1 2
    sh $0 $1 3
    sh $0 $1 4
    sh $0 $1 5
    sh $0 $1 6
    ;;
1)
    run_jplc examples/subtract.jpl >subtract.out
    compare_stdout subtract.out hw1/subtract.out
    ;;
2)
    run_jplc examples/red.jpl
    compare_png red.png hw1/red.png
    ;;
3)
    run_jplc examples/circle.jpl
    compare_png circle.png hw1/circle.png
    ;;
4)
    run_jplc examples/invert.jpl
    compare_png sample-inverted.png hw1/sample-inverted.png
    ;;
5)
    run_jplc examples/sepia.jpl
    compare_png sample-sepia.png hw1/sample-sepia.png
    ;;
6)
    run_jplc examples/blur.jpl
    compare_png sample-blurry.png hw1/sample-blurry.png
    ;;
*)
    echo "USAGE: make test-hw1 DIR=$DIR PART=$PART"
    echo "$PART can be any of all $(seq 1 $($0 count))"
    ;;
esac
