#!/bin/sh
set -e -x

DIR="$1"
PART="$2"

run_jplc () {
    curl -L https://github.com/utah-cs4470-sp23/class/releases/latest/download/jplc-linux -o ./jplc
    chmod +x jplc
    FILE="$1"
    ./jplc --eval "$DIR/$1"
}

compare_stdout () {
    FILE1="$1"
    FILE2="$2"
    diff "$FILE1" "$FILE2"
}

compare_png () {
    FILE1="$1"
    FILE2="$2"
    compare -metric AE -fuzz 1% "$FILE1" "$FILE2" null:
    ERR=$?
    echo
    return $ERR
}

sudo apt-get install -y imagemagick
cp hw1/sample.png sample.png

case $PART in
    all)
        "$0" 1
        "$0" 2
        "$0" 3
        "$0" 4
        "$0" 5
        "$0" 6
        ;;
    1)
        run_jplc examples/subtract.jpl > subtract.out
        compare_stdout subtract.out hw1/subtract.out
        ;;
    2)
        run_jplc examples/red.jpl
        compare_png red.png hw1/red.png
        ;;
    3)
        run_jplc examples/circle.jpl
        compare_png circle.png hw1/circle.png
        ;;
    4)
        run_jplc examples/invert.jpl
        compare_png sample-inverted.png hw1/sample-inverted.png
        ;;
    5)
        run_jplc examples/sepia.jpl
        compare_png sample-sepia.png hw1/sample-blurry.png
        ;;
    6)
        run_jplc examples/blur.jpl
        compare_png sample-blurry.png hw1/sample-blurry.png
        ;;
esac
