#!/bin/sh
set -e

DIR="$1"
PART="$2"

function get_jplc () {
    curl https://github.com/utah-cs4470-sp23/class/releases/download/latest/jplc-linux -o jplc
}

function run_jpl () {
    curl https://github.com/utah-cs4470-sp23/class/releases/download/latest/jplc-linux -o ./jplc
    FILE="$1"
    ./jplc --eval "$DIR/$1"
}

function compare_stdout () {
    FILE1="$1"
    FILE2="$2"
    diff "$FILE1" "$FILE2"
}

function compare_png () {
    FILE1="$1"
    FILE2="$2"
    magick compare -metric AE -fuzz 1% "$FILE1" "$FILE2"
}

case $PART in
    all)
        "$0" 1
        "$0" 2
        "$0" 3
        "$0" 4
        "$0" 5
        "$0" 6
        ;;
    1)
        run_jplc examples/subtract.jpl > subtract.out
        compare_stdout subtract.out hw1/subtract.out
        ;;
    2)
        run_jplc examples/red.jpl
        compare_png red.png hw1/red.png
        ;;
    3)
        run_jplc examples/circle.jpl
        compare_png circle.png hw1/circle.png
        ;;
    4)
        run_jplc examples/invert.jpl
        compare_png sample-inverted.png hw1/sample-inverted.png
        ;;
    5)
        run_jplc examples/sepia.jpl
        compare_png sample-sepia.png hw1/sample-blurry.png
        ;;
    6)
        run_jplc examples/blur.jpl
        compare_png sample-blurry.png hw1/sample-blurry.png
        ;;
esac
