#!/bin/sh

CHILDREN=""
trap 'kill $CHILDREN' INT TERM

sh hw2/test-part "$1" rapidall &
CHILDREN="$CHILDREN $!"
sh hw3/test-part "$1" rapidall &
CHILDREN="$CHILDREN $!"
sh hw4/test-part "$1" rapidall &
CHILDREN="$CHILDREN $!"

wait $CHILDREN
