#!/usr/bin/env perl

use strict;
use warnings;
use autodie;
use File::Spec;

my $compiler = $ARGV[0];
die "specify the compiler" unless defined $compiler;

my $exe = File::Spec->rel2abs($0);
die unless ($exe =~ /^(.*)\/test\-lexer1$/);
my $testdir = "${1}/lexer-tests1";
print "$testdir\n";

my @files = glob "$testdir/*.jpl";

foreach my $f (@files) {
    print "$f : ";
    my $cmd = "make run TEST=$f | tail -n-1 $f.my-output";
    system $cmd;
    my $res = system "diff -c $f.my-output $f.output";
    exit(0) if ($res != 0);
    print "pass\n";
}

print "All tests pass.\n";

