#!/bin/sh
set -e

DIR="$1"
PART="$2"
# From https://stackoverflow.com/questions/29832037/how-to-get-script-directory-in-posix-sh
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)



test1() {
    PROG="$1"
    OUT="$2"
    make --silent --no-print-directory -C "$DIR" run TEST="$PROG" > "$HERE"/out.txt
    printf "%s : " $(basename "$PROG")
    diff -c "$HERE/out.txt" "$OUT" && echo pass
}

test2() {
    PROG="$1"
    printf "%s : " $(basename "$PROG")
    make --silent --no-print-directory -C "$DIR" run TEST="$PROG" > "$HERE"/out.txt
    if grep -c "Compilation succeeded" "$HERE"/out.txt >/dev/null && \
        ! grep -c "Compilation failed" "$HERE"/out.txt >/dev/null; then
        echo "pass"
    else
        echo "fail: file should have lexed"
        echo "======= Output ======="
        cat "$HERE"/out.txt
        echo "======================"
        return 1
    fi
}

test3() {
    PROG="$1"
    printf "%s : " $(basename "$PROG")
    make --silent --no-print-directory --ignore-errors -C "$DIR" run TEST="$PROG" > "$HERE"/out.txt
    if ! grep -c "Compilation succeeded" "$HERE"/out.txt >/dev/null && \
        grep -c "Compilation failed" "$HERE"/out.txt >/dev/null; then
        echo "pass"
    else
        echo "fail: file should not have lexed"
        echo "======= Output ======="
        cat "$HERE"/out.txt
        echo "======================"
        return 1
    fi
}

forall () {
    TESTS="$1"
    shift
    
    count=0
    total=0
    for f in "$TESTS"/*.jpl; do
        if "$@" "$f" "$f".output; then
            count=$((count+1))
        else
            : pass
        fi
        total=$((total+1))
    done
    echo Passed $count out of $total
    test "$count" -eq "$total"
}

case $PART in
    count)
        echo 3
        ;;
    all)
        "$0" 1
        "$0" 2
        "$0" 3
        ;;
    1)
        forall "$HERE"/lexer-tests1 test1
        ;;
    2)
        forall "$HERE"/lexer-tests2 test2
        ;;
    3)
        forall "$HERE"/lexer-tests3 test3
        ;;
    *)
        echo "USAGE: make test-hw2 DIR=$DIR PART=$PART"
        echo "$PART can be any of all $(seq 1 $($0 count))"
        ;;
esac
