#!/bin/sh
set -e

DIR="$1"
PART="$2"
# From https://stackoverflow.com/questions/59895/
HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

jpl () {
    # ./jplc "$@"
    python3 ~/jpl/pavpan/compile.py "$@"
}

test_ok() {
    PROG="$1"
    OUT="$2"
    printf "%s : " $(basename "$PROG")
    make -C "$DIR" run TEST="$PROG" | tail -n+2 > "$HERE"/out.txt
    if ! grep -c "Compilation succeeded" "$HERE"/out.txt >/dev/null ||
       grep -c "Compilation failed" "$HERE"/out.txt >/dev/null; then
        echo "fail: file should have parsed"
        return 1
    fi
    sed "\$d" "$HERE"/out.txt | jpl --pp-sexp - | sed "\$d"> "$HERE"/out.pp
    jpl --pp-sexp "$OUT" | sed "\$d"> "$HERE"/expected.pp
    diff -c "$HERE/out.pp" "$HERE/expected.pp" && echo pass
}

test_fail() {
    PROG="$1"
    printf "%s : " $(basename "$PROG")
    make -C "$DIR" run TEST="$PROG" | tail -n+2 > "$HERE"/out.txt
    if ! grep -c "Compilation succeeded" "$HERE"/out.txt >/dev/null && \
        grep -c "Compilation failed" "$HERE"/out.txt >/dev/null; then
        echo "pass"
    else
        echo "fail: file should not have parsed"
        return 1
    fi
}

regen() {
    PROG="$1"
    OUT="$2"
    printf "%s ...\n" $(basename "$PROG")
    make -C "$DIR" run TEST="$PROG" | tail -n+2 > "$HERE"/out.txt
    sed "\$d" "$HERE"/out.txt | jpl --pp-sexp - | sed "\$d"> "$OUT"
}

case $PART in
    count)
        echo 5
        ;;
    all)
        "$0" 1
        "$0" 2
        "$0" 3
        "$0" 4
        "$0" 5
        ;;
    regen)
        for f in "$HERE"/ok/*.jpl; do
            regen "$f" "$f".expected
        done
        echo Regenerated all tests.
        ;;
    1)
        for f in "$HERE"/ok/*.jpl; do
            test_ok "$f" "$f".expected
        done
        echo All tests pass.
        ;;
    2)
        for f in "$HERE"/ok-fuzzer/*.jpl; do
            test_ok "$f" "$f".expected
        done
        echo All tests pass.
        ;;
    3)
        for f in "$HERE"/fail-fuzzer1/*.jpl; do
            test_fail "$f"
        done
        echo All tests pass.
        ;;
    4)
        for f in "$HERE"/fail-fuzzer2/*.jpl; do
            test_fail "$f"
        done
        echo All tests pass.
        ;;
    5)
        for f in "$HERE"/fail-fuzzer3/*.jpl; do
            test_fail "$f"
        done
        echo All tests pass.
        ;;
    *)
        echo "USAGE: make test-hw2 DIR=$DIR PART=$PART"
        echo "$PART can be any of all $(seq 1 $($0 count))"
        ;;
esac
